### ISSUE TITLE
Re: Error

### ISSUE THREAD

**Issue by nmskhan** [benoitberanger/mp2rage#4]
Hi
Thanks for sharing your scripts for processing MP2RAGE. I tried to run the Matlab scripts, it is giving error like and it has same error in running remove background. Please let me know how to fix that. I am using spm12 and R2019b Is this related to MATLAB version? Thanks
Ned

7-Nov-2020 11:11:12 - Running 'Interactive remove background'
[mp2rage_run_remove_background]: Final output = /Users/Desktop/Fmri/uni/clean_s201007152011DST131221107524366082-0006-00001-000001-01.nii,1 
17-Nov-2020 11:11:16 - Failed  'Interactive remove background'
Error using nifti/subsasgn>assigndat (line 384)
Unknown filename extension (.nii,1).
In file "/Users/khan/Documents/MATLAB/spm12/@nifti/subsasgn.m" (v7370), function "assigndat" at line 384.
In file "/Users/khan/Documents/MATLAB/spm12/@nifti/subsasgn.m" (v7370), function "fun" at line 76.
In file "/Users/khan/Documents/MATLAB/spm12/@nifti/subsasgn.m" (v7370), function "subsasgn" at line 20.
In file "/Users/khan/Documents/MATLAB/spm12/spm_create_vol.m" (v7455), function "create_vol" at line 107.
In file "/Users/khan/Documents/MATLAB/spm12/spm_create_vol.m" (v7455), function "spm_create_vol" at line 17.
In file "/Users/khan/Documents/MATLAB/spm12/spm_write_vol.m" (v5731), function "spm_write_vol" at line 83.
In file "/Users/khan/Documents/MATLAB/spm12/toolbox/mp2rage-master/mp2rage_run_remove_background.m" (???), function "mp2rage_run_remove_background" at line 100.
In file "/Users/Documents/MATLAB/spm12/toolbox/mp2rage-master/mp2rage_cfg_matlabbatch.m" (???), function "prog_rmbg" at line 326.

The following modules did not run:
Failed: Interactive remove background

**Comment by benoitberanger** [comment]
Hi Ned,

Thanks for the log !
The problem should be solved with 752c66fbefce6e8ce32bf492d7b94b8b2a80fad9.
Please try again after updating the code. Let me know if it works.

Best,
Benoît

**Comment by nmskhan** [comment]
Thank you very much for fixing it quickly. It works now.

**Comment by benoitberanger** [comment]
Nice !
